ColorConfigTranslations = {
    "rot": "red",
    "dunkelrot": "darkred",
    "helles korallrot": "lightcoral",
    "feuerrot": "firebrick",
    "braun": "brown",
    "indianerrot": "indianred",
    "dunkles rosa": "rosybrown",
    "kastanienbraun": "maroon",
    "helles rosa": "mistyrose",
    "lachsrosa": "salmon",
    "tomatenrot": "tomato",
    "dunkles lachsrosa": "darksalmon",
    "korallenrot": "coral",
    "orangerot": "orangered",
    "helles lachsrosa": "lightsalmon",
    "siennabraun": "sienna",
    "schokoladenbraun": "chocolate",
    "umbra": "saddlebrown",
    "muschelschale": "seashell",
    "puder, pfirsichrosa": "peachpuff",
    "sandbraun": "sandybrown",
    "leinen": "linen",
    "braun": "per",
    "biskuit": "bisque",
    "dunkles orange": "darkorange",
    "altweiß": "antiquewhite",
    "hautfarben": "tan",
    "blasses orange": "burlywood",
    "mandelfarben": "blanchedalmond",
    "blasses orangegelb": "navajowhite",
    "helles orangegelb": "papayawhip",
    "helles orange": "moccasin",
    "old lace": "oldlace",
    "weizengelb": "wheat",
    "orange": "orange",
    "blütenweiß": "floralwhite",
    "goldrute": "goldenrod",
    "dunkle goldrute": "darkgoldenrod",
    "helles maisgelb": "cornsilk",
    "gold": "gold",
    "khaki, erdfarben": "khaki",
    "zartes zitronengelb": "lemonchiffon",
    "blasse goldrute": "palegoldenrod",
    "dunkler erdton": "darkkhaki",
    "beige": "beige",
    "helles blasses gelb": "lightgoldenrodyellow",
    "elfenbein": "ivory",
    "hellgelb": "lightyellow",
    "gelb": "yellow",
    "olive": "olive",
    "gelbgrün": "yellowgreen",
    "graugrün": "olivedrab",
    "dunkles olivegrün": "darkolivegreen",
    "grüngelb": "greenyellow",
    "chartreuse": "chartreuse",
    "grasgrün": "lawngreen",
    "honigmelone": "honeydew",
    "hellgrün": "lightgreen",
    "blasses grün": "palegreen",
    "blasses grün": "darkseagreen",
    "limonengrün": "limegreen",
    "limone": "lime",
    "wald grün": "forestgreen",
    "grün": "green",
    "dunkelgrün": "darkgreen",
    "seegrün": "seagreen",
    "mittleres seegrün": "mediumseagreen",
    "mintgrün": "mintcream",
    "frühlingsgrün": "springgreen",
    "mittleres frühlingsgrün": "mediumspringgreen",
    "aquamarin": "aquamarine",
    "mittleres aquamarin": "mediumaquamarine",
    "türkis": "turquoise",
    "leichtes seegrün": "lightseagreen",
    "mittleres türkis": "mediumturquoise",
    "himmelbla": "azure",
    "helles zyan": "lightcyan",
    "blasses türkis": "paleturquoise",
    "zyan": "cyan",
    "aquamarinbla": "aqua",
    "petrol": "darkslategray",
    "dunkles zyan": "darkcyan",
    "blaugrün": "teal",
    "dunkeltürkis": "darkturquoise",
    "kadettbla": "cadetblue",
    "puderbla": "powderblue",
    "tiefes himmelbla": "deepskyblue",
    "hellbla": "lightblue",
    "himmelbla": "skyblue",
    "helles himmelbla": "lightskyblue",
    "stahl bla": "steelblue",
    "alice bla": "aliceblue",
    "dodger bla": "dodgerblue",
    "helles schiefer gra": "lightslategray",
    "schiefer gra": "slategray",
    "helles stahlbla": "lightsteelblue",
    "kornblumenbla": "cornflowerblue",
    "königsbla": "royalblue",
    "marinebla": "navy",
    "mitternachtsbla": "midnightblue",
    "mittelbla": "mediumblue",
    "flieder, fliederblau, lavendel": "lavender",
    "weiß mit blaustich": "ghostwhite",
    "bla": "blue",
    "dunkelbla": "darkblue",
    "schlieferbla": "slateblue",
    "dunkles schieferbla": "darkslateblue",
    "mittleres schieferbla": "mediumslateblue",
    "mittleres purpur": "mediumpurple",
    "rebecca lila": "rebeccapurple",
    "blau violett": "blueviolet",
    "indigobla": "indigo",
    "dunkle orchidee": "darkorchid",
    "dunkelviolett": "darkviolet",
    "mittel orchidee": "mediumorchid",
    "distelbla": "thistle",
    "pflaumenbla": "plum",
    "violett": "violet",
    "magenta, fuchsie": "magenta",
    "fuchsie, magenta": "fuchsia",
    "dunkles magenta": "darkmagenta",
    "purpur": "purple",
    "helles violett": "orchid",
    "violettrot": "mediumvioletred",
    "kräftiges pink": "deeppink",
    "leuchtendes pink": "hotpink",
    "blasses lila": "palevioletred",
    "heller fliederton": "lavenderblush",
    "purpur": "crimson",
    "pink": "pink",
    "helles pink": "lightpink",
    "weiß mit rotstich": "snow",
    "weiß": "white",
    "zartes hellgra": "whitesmoke",
    "hellgra": "gainsboro",
    "hellgrau, silbergra": "lightgrey",
    "silber": "silver",
    "dunkelgra": "darkgray",
    "gra": "gray",
    "dunkelgra": "dimgray",
    "schwarz": "black",
}
