# -*- coding: utf-8 -*-

ColorConfigTranslations = {
    u"rot": u"red",
    u"dunkelrot": u"darkred",
    u"helles korallrot": u"lightcoral",
    u"feuerrot": u"firebrick",
    u"braun": u"brown",
    u"indianerrot": u"indianred",
    u"dunkles rosa": u"rosybrown",
    u"kastanienbraun": u"maroon",
    u"helles rosa": u"mistyrose",
    u"lachsrosa": u"salmon",
    u"tomatenrot": u"tomato",
    u"dunkles lachsrosa": u"darksalmon",
    u"korallenrot": u"coral",
    u"orangerot": u"orangered",
    u"helles lachsrosa": u"lightsalmon",
    u"siennabraun": u"sienna",
    u"schokoladenbraun": u"chocolate",
    u"umbra": u"saddlebrown",
    u"muschelschale": u"seashell",
    u"puder, pfirsichrosa": u"peachpuff",
    u"sandbraun": u"sandybrown",
    u"leinen": u"linen",
    u"braun": u"peru",
    u"biskuit": u"bisque",
    u"dunkles orange": u"darkorange",
    u"altweiß": u"antiquewhite",
    u"hautfarben": u"tan",
    u"blasses orange": u"burlywood",
    u"mandelfarben": u"blanchedalmond",
    u"blasses orangegelb": u"navajowhite",
    u"helles orangegelb": u"papayawhip",
    u"helles orange": u"moccasin",
    u"old lace": u"oldlace",
    u"weizengelb": u"wheat",
    u"orange": u"orange",
    u"blütenweiß": u"floralwhite",
    u"goldrute": u"goldenrod",
    u"dunkle goldrute": u"darkgoldenrod",
    u"helles maisgelb": u"cornsilk",
    u"gold": u"gold",
    u"khaki, erdfarben": u"khaki",
    u"zartes zitronengelb": u"lemonchiffon",
    u"blasse goldrute": u"palegoldenrod",
    u"dunkler erdton": u"darkkhaki",
    u"beige": u"beige",
    u"helles blasses gelb": u"lightgoldenrodyellow",
    u"elfenbein": u"ivory",
    u"hellgelb": u"lightyellow",
    u"gelb": u"yellow",
    u"olive": u"olive",
    u"gelbgrün": u"yellowgreen",
    u"graugrün": u"olivedrab",
    u"dunkles olivegrün": u"darkolivegreen",
    u"grüngelb": u"greenyellow",
    u"chartreuse": u"chartreuse",
    u"grasgrün": u"lawngreen",
    u"honigmelone": u"honeydew",
    u"hellgrün": u"lightgreen",
    u"blasses grün": u"palegreen",
    u"blasses grün": u"darkseagreen",
    u"limonengrün": u"limegreen",
    u"limone": u"lime",
    u"wald grün": u"forestgreen",
    u"grün": u"green",
    u"dunkelgrün": u"darkgreen",
    u"seegrün": u"seagreen",
    u"mittleres seegrün": u"mediumseagreen",
    u"mintgrün": u"mintcream",
    u"frühlingsgrün": u"springgreen",
    u"mittleres frühlingsgrün": u"mediumspringgreen",
    u"aquamarin": u"aquamarine",
    u"mittleres aquamarin": u"mediumaquamarine",
    u"türkis": u"turquoise",
    u"leichtes seegrün": u"lightseagreen",
    u"mittleres türkis": u"mediumturquoise",
    u"himmelblau": u"azure",
    u"helles zyan": u"lightcyan",
    u"blasses türkis": u"paleturquoise",
    u"zyan": u"cyan",
    u"aquamarinblau": u"aqua",
    u"petrol": u"darkslategray",
    u"dunkles zyan": u"darkcyan",
    u"blaugrün": u"teal",
    u"dunkeltürkis": u"darkturquoise",
    u"kadettblau": u"cadetblue",
    u"puderblau": u"powderblue",
    u"tiefes himmelblau": u"deepskyblue",
    u"hellblau": u"lightblue",
    u"himmelblau": u"skyblue",
    u"helles himmelblau": u"lightskyblue",
    u"stahl blau": u"steelblue",
    u"alice blau": u"aliceblue",
    u"dodger blau": u"dodgerblue",
    u"helles schiefer grau": u"lightslategray",
    u"schiefer grau": u"slategray",
    u"helles stahlblau": u"lightsteelblue",
    u"kornblumenblau": u"cornflowerblue",
    u"königsblau": u"royalblue",
    u"marineblau": u"navy",
    u"mitternachtsblau": u"midnightblue",
    u"mittelblau": u"mediumblue",
    u"flieder, fliederblau, lavendel": u"lavender",
    u"weiß mit blaustich": u"ghostwhite",
    u"blau": u"blue",
    u"dunkelblau": u"darkblue",
    u"schlieferblau": u"slateblue",
    u"dunkles schieferblau": u"darkslateblue",
    u"mittleres schieferblau": u"mediumslateblue",
    u"mittleres purpur": u"mediumpurple",
    u"rebecca lila": u"rebeccapurple",
    u"blau violett": u"blueviolet",
    u"indigoblau": u"indigo",
    u"dunkle orchidee": u"darkorchid",
    u"dunkelviolett": u"darkviolet",
    u"mittel orchidee": u"mediumorchid",
    u"distelblau": u"thistle",
    u"pflaumenblau": u"plum",
    u"violett": u"violet",
    u"magenta, fuchsie": u"magenta",
    u"fuchsie, magenta": u"fuchsia",
    u"dunkles magenta": u"darkmagenta",
    u"purpur": u"purple",
    u"helles violett": u"orchid",
    u"violettrot": u"mediumvioletred",
    u"kräftiges pink": u"deeppink",
    u"leuchtendes pink": u"hotpink",
    u"blasses lila": u"palevioletred",
    u"heller fliederton": u"lavenderblush",
    u"purpur": u"crimson",
    u"pink": u"pink",
    u"helles pink": u"lightpink",
    u"weiß mit rotstich": u"snow",
    u"weiß": u"white",
    u"zartes hellgrau": u"whitesmoke",
    u"hellgrau": u"gainsboro",
    u"hellgrau, silbergrau": u"lightgrey",
    u"silber": u"silver",
    u"dunkelgrau": u"darkgray",
    u"grau": u"gray",
    u"dunkelgrau": u"dimgray",
    u"schwarz": u"black",
}
